version: "3"

services:
  be-compose:
    image: vulebaolong/img-be_cyber_media:latest
    container_name: cons-be_cyber_media
    ports:
      - "3070:3069"
    depends_on:
      - mysql-compose
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRES=${ACCESS_TOKEN_EXPIRES}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES}
    command: ["npm", "run", "start"]

  mysql-compose:
    image: mysql
    container_name: some-mysql-compose
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"