name: CD docker

on:
   workflow_run:
      workflows: ["CI docker"]
      types:
         - completed

jobs:
   build:
      runs-on: node_fe

      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      steps:
         - name: Stop running containers
           run: sudo docker stop cons_node_fe || true

         - name: Remove containers
           run: sudo docker rm cons_node_fe || true

         - name: Delete old docker image
           run: sudo docker rmi vulebaolong/img_node_fe:latest || true

         - name: Pull Docker image
           run: sudo docker pull vulebaolong/img_node_fe:latest || true

         - name: Run Docker Compose
           run: |
              sudo docker run -d -p 5173:80 --name cons_node_fe vulebaolong/img_node_fe:latest
